name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20  # 使用 Node.js 18，根据你的项目需要调整

            - name: Install dependencies
              run: npm install  # 或 yarn install, pnpm install

            - name: Run tests (optional)
              run: npm run test  # 或 yarn test, pnpm test (确保你有测试脚本)

            - name: Build project
              run: npm run build  # 或 yarn build, pnpm build (根据你的构建脚本调整)

            - name: Upload production-ready build files
              uses: actions/upload-pages-artifact@v3
              with:
                  name: production-files
                  path: ./dist  # Vue CLI 默认的输出目录，如果不同请修改

    deploy:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            pages: write      # to deploy to Pages
            id-token: write   # to verify the deployment originates from an appropriate source

        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
              with:
                  artifact_name: production-files # name of the artifact to deploy